const imagePaths = {
  mainBg: "/assets/images/backgrounds/background-open-poen.png",
  signupBg: "/assets/images/backgrounds/background-sign-up.jpg",
  close: "/assets/images/icons/icon-close.svg",
  closePreview: "/assets/images/icons/icon-close-preview.svg",
  deleteRed: "/assets/images/icons/icon-delete-red.svg",
  delete: "/assets/images/icons/icon-delete.svg",
  edit: "/assets/images/icons/icon-edit.svg",
  view: "/assets/images/icons/icon-view.svg",
  funds: "/assets/images/icons/icon-funds.svg",
  home: "/assets/images/icons/icon-home.svg",
  login: "/assets/images/icons/icon-login.svg",
  connector: "/assets/images/icons/icon-connector.svg",
  logout: "/assets/images/icons/icon-logout.svg",
  return: "/assets/images/icons/icon-return.svg",
  right: "/assets/images/icons/icon-right-arrow.svg",
  settings: "/assets/images/icons/icon-settings.svg",
  search: "/assets/images/icons/icon-search.svg",
  sponsors: "/assets/images/icons/icon-sponsors.svg",
  transactions: "/assets/images/icons/icon-transactions.svg",
  users: "/assets/images/icons/icon-users.svg",
  profile: "/assets/images/icons/icon-profile.svg",
  sponsor: "/assets/images/icons/icon-sponsor-blue.svg",
  upload: "/assets/images/icons/icon-upload.svg",
  hidePass: "/assets/images/icons/icon-closed-eye.svg",
  show: "/assets/images/icons/icon-open-eye.svg",
  succes: "/assets/images/icons/icon-succes.svg",
  linkOwner: "/assets/images/icons/icon-link-owner.svg",
  inputPassword: "/assets/images/icons/icon-input-password.svg",
  inputUsername: "/assets/images/icons/icon-input-username.svg",
  changePassword: "/assets/images/icons/icon-change-password.svg",
  logoGradient: "/assets/images/logos/logo-openpoen-gradient.svg",
  logoLogin: "/assets/images/logos/logo-openpoen-login.svg",
  logoMain: "/assets/images/logos/logo-openpoen.svg",
  logoMobile: "/assets/images/logos/logo-openpoen-mobile.svg",
  placeholderProfile: "/assets/images/placeholders/placeholder-profile.png",
  sandboxLogo: "/assets/images/logos/logo-sandbox-bank.png",
};

export default imagePaths;

export type ImagePaths = typeof imagePaths;
